/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { markdown_frontmatter$_T } from './markdown_frontmatter$_b'
export interface markdown_ctx_I {
	markdown_frontmatter$?:markdown_frontmatter$_T
}