/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import { be_ } from '@ctx-core/object'
import type { markdown_Ctx } from './markdown_Ctx'
import type { markdown_frontmatter$_T } from './markdown_frontmatter$_b'
import { markdown_frontmatter$_b } from './markdown_frontmatter$_b'
export interface markdown_ctx_I {
	markdown_frontmatter$?:markdown_frontmatter$_T
	markdown_b_h?:markdown_b_h_T
}
export interface markdown_b_h_T {
	get markdown_frontmatter$():markdown_frontmatter$_T
}
export function markdown_b_h_b(ctx:markdown_Ctx):markdown_b_h_T {
	return be_<markdown_Ctx, 'markdown_b_h'>('markdown_b_h', ()=>{
		return {
			get markdown_frontmatter$() { return markdown_frontmatter$_b(ctx) }
		}
	})(ctx)
}
